image:
  repository: dkrinitsyn/llm-broker
  pullPolicy: Always
  tag: "20260622183343"

ollama:
  image: ollama/ollama:latest
  port: 11434
  hostModelPath: /var/lib/ollama

nodeSelectorValues:
  - ksai
  - kmai

brokerPort: 8000

env:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local/"
  REQUEST_QUEUE: "llm_requests"
  OLLAMA_URL: "http://localhost:11434"
  OLLAMA_MODEL: "llama3.2:3b"

namespace:  
