image:
  repository: dkrinitsyn/llm-broker
  pullPolicy: Always
  tag: "20260622195630"

llamacpp:
  binDir: /opt/ollama-build/latest
  modelDir: /var/lib/llama-models

nodeSelectorValues:
  - ksai
  - kmai

brokerPort: 8000

env:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local/"
  REQUEST_QUEUE: "llm_requests"
  LLAMA_BIN_DIR: "/opt/llama-bin"
  LLAMA_MODEL_DIR: "/models"
  LLAMA_PORT: "8080"

namespace:  
